# Generated by Django 5.0.7 on 2024-08-01 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioforum',
            name='comentario',
            field=models.CharField(max_length=100, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comentarioquiz',
            name='comentario',
            field=models.CharField(max_length=100, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='idioma',
            field=models.CharField(max_length=100, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='tamanhofonte',
            field=models.CharField(max_length=100, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='decada',
            name='decada',
            field=models.CharField(max_length=100, verbose_name='Decada'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='decada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.decada', verbose_name='Decada'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fundador',
            field=models.CharField(max_length=100, verbose_name='Nome do Fundador'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais', verbose_name='Pais em que foi fundada'),
        ),
        migrations.AlterField(
            model_name='historiainformatica',
            name='contexto',
            field=models.CharField(max_length=100, verbose_name='Contexto'),
        ),
        migrations.AlterField(
            model_name='historiainformatica',
            name='tipotecnologia',
            field=models.CharField(max_length=100, verbose_name='Tipo da Tecnologia'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pontuacao',
            field=models.CharField(max_length=100, verbose_name='pontuacao'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do usuario'),
        ),
    ]
